name: Caller Workflow

on:
    workflow_dispatch:

jobs:
    greeting:
        runs-on: ubuntu-latest
        steps:
            - name: Call Reusable Workflow
              uses: themickster268/my-reusable-workflows/.github/workflows/called.yml@main
              with:
                actor: Michael Donnelly
